name: GitHub Actions Demo
run-name: Building metahome 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: korandoru/setup-zig@v1.4.0
         with:
            zig-version: master

       - uses: actions/checkout@v3
         with:
          submodules: true
        
       - run: |
          zig build -Drelease-small -Dcpu=baseline -Dtarget=x86_64-linux-gnu
          mv zig-out/bin/metahome zig-out/bin/metahome.x86_64.linux
          
          zig build -Drelease-small -Dcpu=baseline -Dtarget=x86_64-windows-gnu
          mv zig-out/bin/metahome.exe zig-out/bin/metahome.x86_64.windows.exe
          
          zig build -Drelease-small -Dsimon-mode   -Dtarget=x86_64-linux-gnu
          mv zig-out/bin/metahome zig-out/bin/metahome.x86_64.simon.linux
       
       - uses: actions/upload-artifact@v3.1.1
         with:
          name: "Binaries"
          path: metahome/zig-out/bin/*
          error: "aawy"
       
